sac/Controllers/MainLibrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using sac.Models;

namespace sac.Controllers
{
    public class MainLibrosController : Controller
    {
        dbModel db = new dbModel();
        // GET: MainLibros
        public ActionResult Index()
        {
            return View(db.tblLibros.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.idotorgante = new SelectList(db.tblOtorgante, "idotorgante", "nombres");
            ViewBag.idfavorde = new SelectList(db.tblAfavorde, "idfavorde", "nombres");
            return View();
        }
        [HttpPost]
        public ActionResult Create(tblLibros libros)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files[0];
                    if (file.ContentLength > 0)
                    {
                        var img = (file.FileName).ToLower();
                        libros.img = "/Content/Libros/" + img;
                        file.SaveAs(Server.MapPath("~/Content/Libros/") + img);

                    }
                    db.tblLibros.Add(libros);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(libros);
        }
        public ActionResult Edit(int id)
        {
            ViewBag.idotorgante = new SelectList(db.tblOtorgante, "idotorgante", "nombres");
            ViewBag.idfavorde = new SelectList(db.tblAfavorde, "idfavorde", "nombres");
            var datos = db.tblLibros.Find(id);
            return View(datos);
        }
        [HttpPost]
        public ActionResult Edit(tblLibros libros, int id)
        {
            db.Entry(libros).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            var datos = db.tblLibros.Find(id);
            return View(datos);
        }
        public ActionResult Delete(int id)
        {
            var datos = db.tblLibros.Find(id);
            return View(datos);
        }
        [HttpPost]
        public ActionResult Delete(tblLibros libros, int id)
        {
            var datos = db.tblLibros.Where(a => a.idlibros.Equals(id)).FirstOrDefault();

            db.tblLibros.Remove(datos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

sac/Views/MainLibros/Create.cshtml
@model sac.Models.tblLibros

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-xs-12 col-md-3"></div>
<div class="col-xs-12 col-md-6">
    <div class="row">
        <div class="box box-success" style="font-family:Courier New;">
            <div class="box-header">
                <h4 class="box-title" style="font-family:Courier New;"><strong>Registro de "Libros"</strong></h4>
            </div>
            <div class="box-body">
                @using (Html.BeginForm("Create", "MainLibros", FormMethod.Post, new { enctype = "multipart/form-data"}))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                            @Html.LabelFor(model => model.afiliado, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.afiliado, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.afiliado, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.instrumento, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.instrumento, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.instrumento, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.folios, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.folios, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.folios, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.libro, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.libro, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.libro, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.img, new { htmlAttributes = new { type ="file"} })
                                @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.idotorgante, "idotorgante", htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.DropDownList("idotorgante", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.idotorgante, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.idfavorde, "idfavorde", htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.DropDownList("idfavorde", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.idfavorde, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Regresar", "Index", new { },new { @class="btn btn-default"})
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-xs-12 col-md-3"></div>

sac/Views/MainLibros/Delete.cshtml
@model sac.Models.tblLibros

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tblAfavorde.nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblAfavorde.nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblOtorgante.nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblOtorgante.nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.afiliado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.afiliado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.instrumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.instrumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.folios)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.folios)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.libro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

sac/Views/MainLibros/Details.cshtml
@model sac.Models.tblLibros

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-xs-12 col-md-3"></div>
<div class="col-xs-12 col-md-6">
    <div class="row">
        <div class="box box-success" style="font-family:Courier New;">
            <div class="box-header">
                <h4 class="box-title" style="font-family:Courier New;"><strong>Detalles de "Libros"</strong></h4>
            </div>
            <div class="box-body">
                <div>
                    <hr style="margin-top:-10px;"/>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.fecha)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.fecha)
                        </dd>
                        <dt>
                            @*@Html.DisplayNameFor(model => model.tblAfavorde.nombres)*@
                            Otorgante
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.tblOtorgante.nombres)
                        </dd>

                        <dt>
                            @*@Html.DisplayNameFor(model => model.tblOtorgante.nombres)*@
                            A favor de
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.tblAfavorde.nombres)
                        </dd>


                        <dt>
                            @Html.DisplayNameFor(model => model.afiliado)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.afiliado)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.instrumento)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.instrumento)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.folios)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.folios)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.libro)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.libro)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.img)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.img)
                        </dd>

                    </dl>
                </div>
                <p>
                    @Html.ActionLink("Editar", "Edit", new { id = Model.idlibros }, new { @class="btn btn-warning"}) |
                    @Html.ActionLink("Back to List", "Index")
                </p>

            </div>
        </div>
    </div>
</div>
<div class="col-xs-12 col-md-3"></div>

sac/Views/MainLibros/Edit.cshtml
@model sac.Models.tblLibros

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-xs-12 col-md-3"></div>
<div class="col-xs-12 col-md-6">
    <div class="row">
        <div class="box box-success" style="font-family:Courier New;">
            <div class="box-header">
                <h4 class="box-title" style="font-family:Courier New;"><strong>Editar registro de "Libros"</strong></h4>
            </div>
            <div class="box-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <hr style="margin-top:-10px;"/>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.idlibros)

                        <div class="form-group">
                            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                            @Html.LabelFor(model => model.afiliado, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.afiliado, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.afiliado, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.instrumento, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.instrumento, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.instrumento, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.folios, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.folios, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.folios, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.libro, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.libro, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.libro, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.img, new { htmlAttributes = new {type="file" } })
                                @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.idotorgante, "idotorgante", htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.DropDownList("idotorgante", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.idotorgante, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.idfavorde, "idfavorde", htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.DropDownList("idfavorde", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.idfavorde, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Regresar", "Index", new { }, new { @class="btn btn-default"})
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-xs-12 col-md-3"></div>

sac/Views/MainLibros/Index.cshtml
@model IEnumerable<sac.Models.tblLibros>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-xs-12 col-md-12">
    <div class="row">
        <div class="box box-success" style="font-family:Courier New;">
            <div class="box-header">
                <h4 class="box-title" style="font-family:Courier New;"><strong>Listado de "Libros"</strong></h4>
            </div>
            <div class="box-body table-responsive" >
                <p>
                    @Html.ActionLink("Nuevo Registro", "Create", new { },new { @class="btn bg-navy"})
                </p>
                <table class="table table-bordered table-hover table-condensed">
                    <tr>
                        <th>
                            N°
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.fecha)
                        </th>
                        <th>
                            @*@Html.DisplayNameFor(model => model.tblAfavorde.nombres)*@
                            Otorgantes
                        </th>
                        <th>
                            @*@Html.DisplayNameFor(model => model.tblOtorgante.nombres)*@
                            A favor de
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.instrumento)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.folios)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.libro)
                        </th>
                        <th>                            
                            @Html.DisplayNameFor(model => model.img)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.idlibros)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.fecha)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tblOtorgante.nombres)
                        </td>
                        <td>

                            @Html.DisplayFor(modelItem => item.tblAfavorde.nombres)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.instrumento)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.folios)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.libro)
                        </td>
                        <td>
                            @*@Html.DisplayFor(modelItem => item.img)*@
                            <a href="@Html.DisplayFor(modelItem => item.img)" class="btn bg-green fa fa-eye" target="_blank"></a> |
                        </td>
                        <td>
                            @Html.ActionLink(" ", "Edit", new { id = item.idlibros }, new { @class = "fa fa-edit btn bg-black" }) |
                            @Html.ActionLink(" ", "Details", new { id = item.idlibros }, new { @class = "fa fa-folder-open btn bg-aqua" }) |
                            @Html.ActionLink(" ", "Delete", new { id = item.idlibros }, new { @class = "fa fa-trash btn bg-red" })
                        </td>
                    </tr>
                    }

                </table>
            </div>
        </div>
    </div>
</div>